/*
Script generated by Aqua Data Studio 8.0.2 on Nov-13-2009 06:06:23 PM
Database: sempediaprod
Schema: public
Objects: SEQUENCE, RULE, TABLE, VIEW, PROCEDURE, FUNCTION, INDEX, TRIGGER
*/

SET sql_mode='ANSI_QUOTES'



ALTER TABLE "triple" DROP foreign key "object_id" ;


GO
ALTER TABLE "triple"
	DROP CONSTRAINT "fkcc6a0c5e37d36139" CASCADE 
GO
ALTER TABLE "public"."predicate"
	DROP CONSTRAINT "fkafa6a9b7fd1b4d3d" CASCADE 
GO
ALTER TABLE "public"."object"
	DROP CONSTRAINT "fkc300a33ffd1b4d3d" CASCADE 
GO
ALTER TABLE "object_description"
	DROP CONSTRAINT "object_id" CASCADE 
GO
ALTER TABLE "inheritance"
	DROP CONSTRAINT "class_id" CASCADE 
GO
ALTER TABLE "class_description"
	DROP CONSTRAINT "class_id" CASCADE 
GO
DROP INDEX "triple_pkey"
GO
DROP INDEX "predicate_pkey"
GO
DROP INDEX "object_pkey"
GO
DROP INDEX "object_description_pkey"
GO
DROP INDEX "inheritance_pkey"
GO
DROP INDEX "class_pkey"
GO
DROP INDEX "class_description_pkey"
GO
DROP TABLE "triple"
GO
DROP TABLE "predicate"
GO
DROP TABLE "object"
GO
DROP TABLE "object_description"
GO
DROP TABLE "inheritance"
GO
DROP TABLE "class"
GO
DROP TABLE "class_description"
GO
DROP SEQUENCE "hibernate_sequence" 
GO


CREATE SEQUENCE "hibernate_sequence"
GO
CREATE TABLE "class_description"  ( 
	"class_text_id"	int4 NOT NULL,
	"para_style"   	varchar(255) NULL,
	"class_id"     	int4 NULL,
	"para_text"    	varchar(10000) NULL,
	PRIMARY KEY("class_text_id")
)
GO
CREATE TABLE "class"  ( 
	"class_id"  	int4 NOT NULL,
	"class_name"	varchar(255) NULL,
	PRIMARY KEY("class_id")
)
GO
CREATE TABLE "inheritance"  ( 
	"inheritance_id"	int4 NOT NULL,
	"subclass"      	int4 NULL,
	"superclass"    	int4 NULL,
	PRIMARY KEY("inheritance_id")
)
GO
CREATE TABLE "object_description"  ( 
	"object_description_id"	int4 NOT NULL,
	"object_image"         	bytea NULL,
	"object_id"            	int4 NULL,
	"object_desc"          	varchar(10000) NULL,
	PRIMARY KEY("object_description_id")
)
GO
CREATE TABLE "object"  ( 
	"object_id"  	int4 NOT NULL,
	"object_name"	varchar(255) NULL,
	"class_id"   	int4 NULL,
	PRIMARY KEY("object_id")
)
GO
CREATE TABLE "predicate"  ( 
	"predicate_id"  	int4 NOT NULL,
	"predicate_name"	varchar(255) NULL,
	"class_id"      	int4 NULL,
	PRIMARY KEY("predicate_id")
)
GO
CREATE TABLE "triple"  ( 
	"triple_id"   	int4 NOT NULL,
	"predicate_id"	int4 NULL,
	"subject"     	int4 NULL,
	"object"      	int4 NULL,
	PRIMARY KEY("triple_id")
)
GO
CREATE UNIQUE INDEX "class_description_pkey"
	ON "class_description"("class_text_id")
GO
CREATE UNIQUE INDEX "class_pkey"
	ON "class"("class_id")
GO
CREATE UNIQUE INDEX "inheritance_pkey"
	ON "inheritance"("inheritance_id")
GO
CREATE UNIQUE INDEX "object_description_pkey"
	ON "object_description"("object_description_id")
GO
CREATE UNIQUE INDEX "object_pkey"
	ON "object"("object_id")
GO
CREATE UNIQUE INDEX "predicate_pkey"
	ON "predicate"("predicate_id")
GO
CREATE UNIQUE INDEX "triple_pkey"
	ON "triple"("triple_id")
GO

ALTER TABLE "class_description"
	ADD CONSTRAINT "class_id"
	FOREIGN KEY("class_id")
	REFERENCES "class"("class_id")
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
ALTER TABLE "inheritance"
	ADD CONSTRAINT "class_id"
	FOREIGN KEY("superclass")
	REFERENCES "class"("class_id")
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
ALTER TABLE "object_description"
	ADD CONSTRAINT "object_id"
	FOREIGN KEY("object_id")
	REFERENCES "public"."object"("object_id")
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
ALTER TABLE "object"
	ADD CONSTRAINT "fkc300a33ffd1b4d3d"
	FOREIGN KEY("class_id")
	REFERENCES "class"("class_id")
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
ALTER TABLE "predicate"
	ADD CONSTRAINT "fkafa6a9b7fd1b4d3d"
	FOREIGN KEY("class_id")
	REFERENCES "class"("class_id")
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
ALTER TABLE "triple"
	ADD CONSTRAINT "object_id"
	FOREIGN KEY("object")
	REFERENCES "object"("object_id")
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
ALTER TABLE "triple"
	ADD CONSTRAINT "fkcc6a0c5e37d36139"
	FOREIGN KEY("predicate_id")
	REFERENCES "predicate"("predicate_id")
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO

